COPY		START		0
			LDA			ZERO
			LDX			HEX80
CHKDEV		TD			STORAGE
			JEQ			CHKDEV
			LDA			ZERO
			RD			STORAGE
			COMP		HEX04
			JEQ			ENDCOPY
			COMP		ASCII_H
			JEQ			S_COPY
			COMP		ASCII_T
			JEQ			T_COPY
			TIX			STORAGE
			J			CHKDEV
ENDCOPY		J			HEX80
S_COPY		STL			L_STORAGE
			JSUB		S_ROUTINE
			LDL			L_STORAGE
			J			CHKDEV
T_COPY		STL			L_STORAGE
			JSUB		T_ROUTINE
			LDL			L_STORAGE
			J			CHKDEV
.
.	S record sub routine
.
S_ROUTINE	STX			X_STORAGE
			LDX			ZERO
			LDA			ZERO
READSTR		RD			STORAGE
			TIX			SIX
			JLT			READSTR
			JEQ			READSTR
			LDX			ZERO
			LDA			ZERO
READLOC		RD			STORAGE
			STCH		STARTLOC,X
			TIX			TWO
			JLT			READLOC
			STA			TEMPA
			LDA			STARTLOC
			ADD			HEX80
			STA			STARTLOC
			RD			STORAGE
			LDX			X_STORAGE
			RSUB
.
.	T record sub routine
.
T_ROUTINE	STX			X_STORAGE
			LDX			ZERO
			LDA			ZERO
READSTR_T	RD			STORAGE
			STCH		RECORDLOC,X
			TIX			THREE
			JEQ			READSTR_T
			LDA			ZERO
			RD			STORAGE
			STCH		RECORDSIZE
			LDA			RECORDLOC
			ADD			STARTLOC
			STA			RECORDLOC
			ADD			RECORDSIZE
			STA			RECORDSIZE
			LDX			RECORDLOC
READSTR_C	LDA			ZERO
			RD			STORAGE
			STCH		0,X
			TIX			RECORDSIZE
			JEQ			READSTR_C
			LDX			X_STORAGE
			DUMP
			RSUB
ZERO		WORD		0
TWO			WORD		2
THREE		WORD		3
SIX			WORD		6
STORAGE		WORD		1
TEMPA		RESW		1
L_STORAGE	RESW		1
X_STORAGE	RESW		1
STARTLOC	RESW		1
RECORDLOC	RESW		1
RECORDSIZE	RESW		1	
HEX04		BYTE		X'000004'
HEX80		BYTE		X'000080'
ASCII_H		BYTE		X'000048'
ASCII_T		BYTE		X'000054'
ASCII_E		BYTE		C'000045'
			END			COPY